### ISSUE TITLE
Helper to validate params

### ISSUE THREAD

**Issue by martinliptak** [yesmeck/remix-routes#10]
Hey, thanks for this incredible library! Refactoring gets so much easier when I can rely on `$path` helper to check route and param names when generating paths. I was wondering if it makes sense to have a similar helper to bring type safety to reading params.

```typescript
export const action: ActionFunction = async ({ params }) => {
  const { topicId, articleId } = params

  if (!topicId) throw new Error("Missing param: topicId")
  if (!articleId) throw new Error("Missing param: articleId")

  // Use topicId and articleId.
}
```

I could imagine:

```typescript
export const action: ActionFunction = async ({ params }) => {
   const { topicId, articleId } = $params(
    "/user/topics/:topicId/articles/:articleId/finish",
    params
  )

  // Use topicId and articleId.
}
```

Moving the file to a different location would make you update `/user/topics/:topicId/articles/:articleId/finish` and possibly fix changed param names.

Generated code would look like this:

```typescript
const $params = (
  _path: "/user/topics/:topicId/articles/:articleId/finish",
  params: Params<string>
) => params as { topicId: string; articleId: string }
```

If we don't want to rely on Remix that all params from URL are present, we can add a runtime check:

```typescript
const $params = (
  path: "/user/topics/:topicId/articles/:articleId/finish",
  params: Params<string>
) => {
  for (const param of routes[path]) {
    if (!params[param]) {
      throw new Error(`Missing param: ${param}`)
    }
  }

  return params as { topicId: string; articleId: string }
}
```

**Comment by martinliptak** [comment]
I can put together a PR if you like the idea.

**Comment by yesmeck** [comment]
@martinliptak I like the idea, welcome PR.
