### ISSUE TITLE
Separate TypeScript plugin from the remix-routes source code

### ISSUE THREAD

**Issue by tmcw** [yesmeck/remix-routes#108]
I'm attempting to update the TypeScript plugin in #107 (issue upstream at https://github.com/microsoft/TypeScript/issues/59575 ), and not having much luck so far in getting tests to pass. I wonder if the plugin could be not a dependency of the remix-routes module so that there isn't a TS dependency, even an indirect one, by default?

**Comment by yesmeck** [comment]
remix-routes doesn't depend on the plugin actually. I've removed it. Cheers.
