### ISSUE TITLE
Get all routes

### ISSUE THREAD

**Issue by IgnisDa** [yesmeck/remix-routes#116]
Is there a way to get all routes? `remix-routes` already has access to this information. I was wondering if it would be possible to expose this as an array perhaps?

**Comment by yesmeck** [comment]
You can get them from `@remix-run/dev/dist/config` like remix-routes [did](https://github.com/yesmeck/remix-routes/blob/4b1df18094611208d1f9adf0027fb5416af3472c/packages/remix-routes/src/cli.ts#L49).

**Comment by IgnisDa** [comment]
But this is a function and resolved at runtime. Moreover it is not typed. It would be great if it is similar to the `RouteId` type in `remix-routes` that is used by the `$path` helped.

**Comment by IgnisDa** [comment]
If you agree, I can make a PR for this too.

**Comment by yesmeck** [comment]
You can `import type { Routes } from 'remix-routes'` if you want type info of routes.

**Comment by IgnisDa** [comment]
No, as I said in my initial issue description, I need the routes as strings not as types.
