### ISSUE TITLE
Wrong path suggestion

### ISSUE THREAD

**Issue by createdbymahmood** [yesmeck/remix-routes#13]
Hi, 
Thanks for creating such this awesome library, I love type-safe route utilities for all react frameworks like `Next` and this one for `Remix`.

This is my test project's working directory tree view (That `__auth` folder is created because I needed a layout to wrap all auth pages with): 

```
├── __auth
│   └── login.tsx
└── __auth.tsx
```

Which I expect to suggest me `/auth/login` but it shows me `/auth//login` which is a bit wrong.
May you please take a look at this? Thanks!

**Comment by martinliptak** [comment]
Hey, this works for me on remix 1.6.0 and remix-routes 0.2.0. I have `/__auth/sign-in/index.tsx` which translates to `/sign-in` in suggestions.

**Comment by yesmeck** [comment]
@createdbymahmood I can’t reproduce your issue, could create a demo repo?

**Comment by createdbymahmood** [comment]
Here you go.
https://stackblitz.com/edit/github-t2yeyn-atfrcn
