### ISSUE TITLE
How to pass an array as a query string

### ISSUE THREAD

**Issue by Rocinante89** [yesmeck/remix-routes#17]
Not an issue, but a question? I have to pass an array of ID's as a query string. Up to now i've been mapping and appending them to the string like `&id=1&id=2`. Is there a way to achieve this with remix-routes?

**Comment by yesmeck** [comment]
Will #18 solve your problem?

**Comment by Rocinante89** [comment]
@yesmeck looks like it will! Thank you 🙏
