### ISSUE TITLE
In Monorepo with multiple remix projects $path is typed for the last built project

### ISSUE THREAD

**Issue by Rocinante89** [yesmeck/remix-routes#20]
Not sure if this is something you want to put the work into fixing - But we have a monorepo with 2 remix projects, both using remix-routes.

We noticed that the routes on $path reflect the last built project, not matter which project it has been called from. I think it's because the types are generated at the root level. I'll try and get a repo ready after work

**Comment by yesmeck** [comment]
I think it's a bug, I didn't take into account having more than one remix project in a monorepo.

**Comment by yesmeck** [comment]
Can not find a solution to fix this issue. It seems prisma client has the same issue.

**Comment by Rocinante89** [comment]
Cheers! It's easily enough worked around at any rate. We just have to run a new build command when switching what project we are working on
