### ISSUE TITLE
No Types

### ISSUE THREAD

**Issue by leimantas** [yesmeck/remix-routes#24]
No types. Not working.

```
"@remix-run/node": "^1.7.3",
"@remix-run/react": "^1.7.3",
"@remix-run/serve": "^1.7.3",
"remix-routes": "^1.0.0",
```

<img width="858" alt="image" src="https://user-images.githubusercontent.com/46538777/200882043-a9e9e636-be8d-426a-9dd1-9dfdff0acafb.png">

<img width="975" alt="image" src="https://user-images.githubusercontent.com/46538777/200881595-c88043dc-025c-4dbe-a154-3ef8b5b3c09a.png">

<img width="557" alt="image" src="https://user-images.githubusercontent.com/46538777/200881696-222b0c6e-975f-49ab-a4b7-497140bc5891.png">

**Comment by yesmeck** [comment]
Does `node_modules/remix-routes.d.ts` exist?

**Comment by leimantas** [comment]
No, it looks like it's not working at all. 
But cli running

<img width="390" alt="image" src="https://user-images.githubusercontent.com/46538777/200884045-e3f4beb0-970b-459f-be58-1081624e70c6.png">
