### ISSUE TITLE
Feature Request: Optional exporting query param type and making the $path more type safe

### ISSUE THREAD

**Issue by HamadTheIronside** [yesmeck/remix-routes#25]
Hey,

I am using `remix-routes` in my project and it's helpful, but I find a problem with query param typing. 

So my whole idea is the following:

```typescript
// routes/search.tsx

const Page = () => {

}

export type TQuerySearch = {
  productId?: string;
  category?: string;
}

export default Page

// some other file
$path("/search", {
  productId: "okay",
  categoryId: "no okay" // Dude it's an error
})
```

I can help developing it.

**Comment by yesmeck** [comment]
Sounds like a good idea. One thing I'm concerning is what we should name the type. I'd like to propose `SearchParams`.

**Comment by HamadTheIronside** [comment]
The name sounds good to me, can I get the task and complete it? I will get it ready by Sunday.

**Comment by yesmeck** [comment]
@HamadTheIronside Yes, take your time.

**Comment by yesmeck** [comment]
A question comes to my mind, how can we write type for query strings like `?view=gird&sort=price&sort=size`?

**Comment by yesmeck** [comment]
> A question comes to my mind, how can we write type for query strings like `?view=gird&sort=price&sort=size`?

NVM, we can define a type in this way:

```typescript
export type SearchParams = [
    ['view', 'list' | 'grid'],
    ['sort', 'price' | 'brand'],
];
```

**Comment by yesmeck** [comment]
For `?view=gird&id=1&id=2`:

```typescript
export type SearchParams = [
    ['view', 'list' | 'grid'],
    ...Array<['id', number]>
]
```

**Comment by HamadTheIronside** [comment]
> For `?view=gird&id=1&id=2`:
> 
> ```ts
> export type SearchParams = [
>     ['view', 'list' | 'grid'],
>     ...Array<['id', number]>
> ]
> ```

What about?

```typescript
export type SearchParams = [
    ['view', 'list' | 'grid'],
    ['id', number[]]
]
```

**Comment by yesmeck** [comment]
> What about?
> 
> ```ts
> export type SearchParams = [
>     ['view', 'list' | 'grid'],
>     ['id', number[]]
> ]
> ```

It won't work, see [Playground Link](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcDKwCGUDGALABW0wFsBnOAXjgG0AoOR2gcgDcBLYAd2YBo5mAG3ZkYzOAB8BAcyjsAJswC6vBkxrMFfOADsAriQBGwKDSVK6Fujgg7RcMMXIAudFlyEnFajQ0du2syyWiosWvwAjKEa4XAATOYA3EA)

**Comment by HamadTheIronside** [comment]
> > What about?
> > ```ts
> > export type SearchParams = [
> >     ['view', 'list' | 'grid'],
> >     ['id', number[]]
> > ]
> > ```
> 
> It won't work, see [Playground Link](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcDKwCGUDGALABW0wFsBnOAXjgG0AoOR2gcgDcBLYAd2YBo5mAG3ZkYzOAB8BAcyjsAJswC6vBkxrMFfOADsAriQBGwKDSVK6Fujgg7RcMMXIAudFlyEnFajQ0du2syyWiosWvwAjKEa4XAATOYA3EA)

I was thinking more like `[['view', 'grid'], ['id', [1, 2]]]`. but thinking more, you are right. let me test more.

**Comment by yesmeck** [comment]
> BTW, any Idea about how to extract the type from the file without using external libraries? 

A rough idea is directly to import the type from the page file.

```typescript
export declare function $path(
  route: \\"/\\",
  query?: import('../app/routes/index').SearchParams | URLSearchParams
): string;
```

**Comment by HamadTheIronside** [comment]
> 



> > BTW, any Idea about how to extract the type from the file without using external libraries?
> 
> A rough idea is directly to import the type from the page file.
> 
> ```ts
> export declare function $path(
>   route: \\"/\\",
>   query?: import('../app/routes/index').SearchParams | URLSearchParams
> ): string;
> ```

Oh, didn't know if we can do this, won't we encounter some absolute/relative import errors?

By the way, I was thinking what if the param is required, I have a case in my project but I don't know if it's valid to have a required query param, what do you think?

**Comment by yesmeck** [comment]
> Oh, didn't know if we can do this, won't we encounter some absolute/relative import errors?

We can ensure `remix-routes.d.ts` is located in `project/node_modules/remix-routes.d.ts` so it's safe to use relative import here. One thing we need to do is to check whether the type is defined in the page file.

> By the way, I was thinking what if the param is required, I have a case in my project but I don't know if it's valid to have a required query param, what do you think?

If the search params type is defined in the page file then the query param will be required, otherwise, it's optional.
