### ISSUE TITLE
Add SearchParams to $params

### ISSUE THREAD

**Issue by moishinetzer** [yesmeck/remix-routes#30]
# Motivation

Currently to get the Search Parameters of a given page you must `useSearchParams()`.

Given a page which already exports a `SearchParams` type, we can add this to the returned data given to `$params` and also do it in a type-safe way!

# Proposed Usage

/users.tsx
```tsx
export type SearchParams = {
  sort?: 'date' | 'views',
  page?: number,
}

export const loader = async ({ params }: LoaderArgs) => {
  const { sort, page } = $params("/users", params) // Inferred and typed correctly because of 'SearchParams'
  return json({ sort, page })
}

export default function () {
  let { sort, page } = useLoaderData<typeof loader>() // Fully type-safe params too! 🥳
}
```

**Comment by yesmeck** [comment]
`$params` and `SearchParams` are different things. `$params` parses the dynamic params from the URL. In contrast, `SearchParams` is the type for the search portion of the URL. In theory, they could be in conflict, e.g.`/users/:id?id=1`. In addition, `SearchParams` is not always a key/value object, e.g. `/users?id=1&id=2`.

I was thinking of providing an typed `useSearchParams()` version based on `SearchParams` type which returns a typed `URLSearchParams`.

```js
export type SearchParams = {
  sort?: 'date' | 'views',
  page?: number,
}

export default function () {
  const [searchParams] = useSearchParams();

  searchParams.get('sort'); // <== type safe.
}
```

**Comment by moishinetzer** [comment]
I agree tha is more straightforward and less confusing for the user. The only reason I would add it in the $params function is to let the user know it is part of this project which makes it more obvious it is relying on the `SearchParams` type. 

Regardless I think this would probably complete the functionality missing types-wise for remix!

Do you foresee yourself being able to work on this soon? @yesmec

**Comment by yesmeck** [comment]
After some research, I reckon that making the `URLSearchParams` type aware may not be a good idea because a typed URLSearchParams can not guarantee runtime type-safe.  Also, I found this library https://github.com/kiliman/remix-params-helper can guarantee search params are both type and runtime safe.

**Comment by moishinetzer** [comment]
I understand. However, the convenience of utilising the already exported SearchParams seems like a missed opportunity though. Perhaps you would be interested in utilising zod within this, or perhaps being passed a Zod instance to get around the package bloat?

**Comment by moishinetzer** [comment]
Any updates / interest in implementing this?

**Comment by moishinetzer** [comment]
That's a totally valid solution - Thanks!
