### ISSUE TITLE
[Feature]: Support for `flat-routes` (v2) routing convention.

### ISSUE THREAD

**Issue by uceumice** [yesmeck/remix-routes#36]

**Comment by nicksrandall** [comment]
@yesmeck Remix v2 is weeks (maybe days) away, and this new route file convention will become the default. 

That said, I have a few questions:
- Are you open to supporting the v2 route convention in this library? 
- What changes need to happen in this library to support that feature?
- Are you open to somebody submitting a PR to support this?

Thanks for all you do!

**Comment by yesmeck** [comment]
> @yesmeck Remix v2 is weeks (maybe days) away, and this new route file convention will become the default.
> 
> That said, I have a few questions:
> 
> * Are you open to supporting the v2 route convention in this library?
> * What changes need to happen in this library to support that feature?
> * Are you open to somebody submitting a PR to support this?
> 
> Thanks for all you do!

Thank you for bringing this up, I will find some time to look into this next week.

**Comment by yesmeck** [comment]
I found that no changes are required to support v2 route convention.

**Comment by matthiaskarl91** [comment]
Hello,
I had a look into the library recently and I guess we are missing a case which is introduced with v2: 
Given that we have a routes folder structure like this:

- `companies.tsx` (which is our layout route and lets say renders just an `<Outlet />`
- 'companies._index.tsx` (which exports the `type SearchParams`)
- `companies.$companyId.tsx` ... (which should render in the same `<Outlet />`

The current output looks somethink like:
```
...
 "/companies": {
      params: {
      
      },
      query: ExportedQuery<import('../app/routes/companies').SearchParams>,
    };
  
    "/companies/modify/:companyId": {
      params: {
      
        companyId: string | number;
      
      },
      query: ExportedQuery<import('../app/routes/companies.modify.$companyId').SearchParams>,
    };

...
``` 
As you can see, in the whole export the `companies._index.tsx` is skipped. I think we somehow need to skip the generation for the layout route and take the `._index.tsx` file instead.

I checked out the code to try to find the reason behind it but it's quite hard for me to understand fully what's going on. If I can help somehow let me know :)

**Comment by yesmeck** [comment]
Hi @matthiaskarl91 , this was actually a bug, #54 fixes it.

**Comment by matthiaskarl91** [comment]
Nice, thanks! Really appreciate it. Works like a charm
