### ISSUE TITLE
[Bug]: Directory splash routes translate with errors.

### ISSUE THREAD

**Issue by uceumice** [yesmeck/remix-routes#37]
Given the following directory, `some.route.$` with an *index.tsx* file inside of it, CLI generates the following mess:

```typescript
export declare function $params(
  route: "/some/route/:",
  params: { readonly [key: string]: string | undefined }
): {
  : string
};
```

**Comment by yesmeck** [comment]
Is the bare $ a feature of flat routes?

**Comment by uceumice** [comment]
No, not really, a bare $ is working fine with v1 routing convention, which does not implement flat routes. That, I assumed, was the supported routing scheme of `remix-routes`.
