### ISSUE TITLE
Wrapping $path function

### ISSUE THREAD

**Issue by moishinetzer** [yesmeck/remix-routes#38]
## Problem

Sometimes, you want to create a function that wraps the `$path` function. For example, given the following code:

```tsx
import { redirect } from "@remix-run/node";
import { $path } from "remix-routes";

export let action = () => {
  return redirect(
    $path("user/:userId", { userId: 1 })
  )
}

// ...
```

In larger projects where you often follow this pattern, your natural instinct is to make a helper function that takes the same typed params as $path but returns a redirect. For example:

```tsx
import { $path } from "remix-routes";
import { redirect as remixRedirect } from "@remix-run/node";

export function redirect(args: Parameters<typeof $path>) {
  return remixRedirect($path(...args));
}
```

However, something else is needed. Given the implementation uses function overloading, `Parameters` does not infer all the correct type narrows. Instead, it just picks the first option and only allows one route.

This is a [famous issue](https://stackoverflow.com/questions/52760509/typescript-returntype-of-overloaded-function) in the typescript world. I'm not sure the best way to address it or if it's worth addressing, but I assume it would require restructuring how the types are stored.

### Potential Solution/s

An alternative called [routes-gen](https://github.com/sandulat/routes-gen) does this by storing all of the routes in a key-value pair and exposing that to the user, but they don't support all the extra features that remix-routes has such as typed query strings.

Side point, this is a great package I enjoy using a lot!

**Comment by yesmeck** [comment]
I'm exporting route definitions in #40, with the Routes interface, you can wrap your own redirect helper as following.

```typescript
import { Routes } from 'remix-routes';
import { redirect as remixRedirect } from "@remix-run/node";

function redirect<R extends keyof Routes, P extends Routes[R]["params"], Q extends Routes[R]["query"]> (route: R, params: P, query?: Q) {
  const includeParams = route.indexOf('/:') > -1;
  return remixRedirect(
      includeParams ? $path(route as any, params as any, query as any) : $path(route as any, query as any)
  );
}
```

**Comment by moishinetzer** [comment]
This solution is great, but then I would always need to include the empty object for the second parameter regardless if any params are necessary:

```tsx
// Throws error:
redirect("/")

// No error:
redirect("/", {})
```

Is there a way to structure this so that the empty object is not needed?

**Comment by yesmeck** [comment]
> This solution is great, but then I would always need to include the empty object for the second parameter regardless if any params are necessary:
> 
> ```tsx
> // Throws error:
> redirect("/")
> 
> // No error:
> redirect("/", {})
> ```
> 
> @yesmeck Is there a way to structure this so that the empty object is not needed?

To the best of my knowledge, it doesn't seem possible to do it in this way.

**Comment by moishinetzer** [comment]
@mattpocock any takes on this?

**Comment by mattpocock** [comment]
https://www.youtube.com/watch?v=YE_3WwX-Dl8

**Comment by moishinetzer** [comment]
Insanity! You are truly the king of typescript ❤️

**Comment by moishinetzer** [comment]
```ts
export const redirect = <
  Route extends keyof Routes,
  Param extends Routes[Route]["params"],
  Query extends Routes[Route]["query"]
>(
  ...args: Param extends Record<string, never>
    ? [route: Route, query?: Query]
    : [route: Route, params: Param, query?: Query]
) => {
  return args;
};
```

Phenomenal! This is the exact solution. @yesmeck, should I create a PR to add a helpful section called "Recipes" for this and prefix a route?

**Comment by yesmeck** [comment]
@moishinetzer do it.

**Comment by moishinetzer** [comment]
Sure, I'm certain that the codegen could be condensed massively by using this `...args` hack. It's worth investigating.

**Comment by yesmeck** [comment]
Yes, we only need to generate one $path method.
