### ISSUE TITLE
[Suggestion]: Typechecking route id's

### ISSUE THREAD

**Issue by jozefmery** [yesmeck/remix-routes#39]
# Suggestion description
Recently, Remix introduced a new helper hook, namely `useRouteLoaderData` (see [docs](https://remix.run/docs/en/v1/hooks/use-route-loader-data)) that requires a `routeId` parameter, typed unfortunately as a `string`.
I would like to suggest the addition of another helper (e.g. `$routeId`) into this library that type-checks said route id's.

**Comment by yesmeck** [comment]
A new `$routeId` helper has been added to remix-routes@1.6.0. Thanks @dawnmist.

**Comment by SutuSebastian** [comment]
@yesmeck the new `safe-routes@v1.0.0` no longer works in `react-router@v7` due to `$routeId()` input type of route paths (eg: `/blog`) instead of file paths (`routes/blog.tsx`, or `routes/blog/route.tsx`)
