### ISSUE TITLE
Empty params always required

### ISSUE THREAD

**Issue by moishinetzer** [yesmeck/remix-routes#43]
It seems the latest release introduced a bug that requires the second param to always be required, even when the route does not require any paths.

I was surprised the test-suite doesnt catch this, I'll try make a PR for it.

![image](https://user-images.githubusercontent.com/11411486/219903098-415d72a9-940b-4462-80aa-7a068928222e.png)

**Comment by moishinetzer** [comment]
It seems as though whilst this package tests for functionality. However, it doesn't test for type safety specifically. I'm unsure how to approach this, but if you can direct me a bit, I'm happy to do so.

**Comment by jozefmery** [comment]
Furthermore, if there are params, the third parameter is also required. For example: `$path("/foo/:bar", {  bar: "baz" }, {})` works instead of just `$path("/foo/:bar", {  bar: "baz" })`.

**Comment by yesmeck** [comment]
Sorry for the bug, the original generated types are very simple, so I didn't add tests for them. Now they are relatively complex now, I'm adding type check to CI  in #f44

**Comment by yesmeck** [comment]
Should be fixed in 1.4.1
