### ISSUE TITLE
Support for vite

### ISSUE THREAD

**Issue by IgnisDa** [yesmeck/remix-routes#68]
Remix now had integration with vite. Does this project work with it?

**Comment by yesmeck** [comment]
It should work with Vite.

**Comment by IgnisDa** [comment]
@yesmeck It does not I believe. Here is the error.
![image](https://github.com/yesmeck/remix-routes/assets/60938164/3237892c-f9ed-472e-9c9c-c1efa1fe586a)

As you can see, the package in question is already installed. Also, the remix app itself is in a yarn workspace, if it matters.

**Comment by IgnisDa** [comment]
Ah this was not a remix-routes specific error. I fixed it by adding this to my `apps/app/package.json`:
```json
"installConfig": {
		"hoistingLimits": "workspaces"
	},
```
