### ISSUE TITLE
Custom output path

### ISSUE THREAD

**Issue by IgnisDa** [yesmeck/remix-routes#7]
Awesome library!

I am using NX for my remix project. Hence the `node_modules` does not exist in the project directory (but instead in the monorepo root). It would be preferable if I could change the output path to a custom one (eg: `app/generated/routes.ts`) and import that as `import { path } from '~/app/generated/routes'`.

**Comment by Rocinante89** [comment]
Similar situation here except we are using turborepo. In turborepos case, The `.remix-routes` folder gets dumped into the project `node-modules` instead of the root. If you manually move it all works as expected. 

Awesome lib though! Would love to be able to use it

**Comment by yesmeck** [comment]
It works with workspace/monorepo out of the box now.
