### ISSUE TITLE
Remix 2.0 support

### ISSUE THREAD

**Issue by cjsauer** [yesmeck/remix-routes#80]
There seem to be a couple subtle type differences between the tests Remix `1.9.0` version and the latest `2.5.0`. I figure it might be helpful to collect the breaking changes in an issue as they're discovered.

The only one I've encountered so far is with the newest `useParams` hook. I receive the following type error when attempting to follow the readme:

```typescript
  const {accountId, propertyId} = useParams<Routes['/dashboard/accounts/:accountId/properties/:propertyId']['params']>()
```

![image](https://github.com/yesmeck/remix-routes/assets/2013873/ca8b2f2d-933a-42a6-8aca-13409d4b2a2f)

This seems to be due to the fact that the latest Remix uses a more recent version of react router that has changed the type of [`useParams`](https://github.com/remix-run/react-router/blob/fb0f1f94778f4762989930db209e6a111504aa63/packages/react-router/lib/hooks.tsx#L293). Specifically it seems that params can no longer be `string | number`, but must be `string | undefined`. 

The obvious fix would be to adjust the type of this block here: https://github.com/yesmeck/remix-routes/blob/96d47691c941cab67941370e8e1aedb50382604b/packages/remix-routes/src/template.ts#L14-L18

Of course, this would be a breaking change, so care would need to be taken.

**Comment by yesmeck** [comment]
The `params` type is not intended to be used for `useParams`. The `$params` helper function is used instead.

**Comment by chimame** [comment]
Maybe it can be solved by modifying the documentation?

**Comment by yesmeck** [comment]
Closing as we encourage using the $params helper for params type inference now.
