### ISSUE TITLE
Is it supposed to work with flat-routes?

### ISSUE THREAD

**Issue by adaboese** [yesmeck/remix-routes#81]
I am using https://github.com/kiliman/remix-flat-routes

The generated file only contains `/` route definition.

Seems to not pick up other routes.

Wondering if mistake in my setup or something else.

**Comment by yesmeck** [comment]
I haven't tested it, but it should work with remix-flat-routes. I will have a look later.

**Comment by yesmeck** [comment]
It doesn't matter whether you use Vite or not. However, if `vite.config.ts` is not loaded, it seems to be an issue with the way you are using Remix.

**Comment by yesmeck** [comment]
`remix-routes` doesn't load `vite.config.ts`, but `@remix-run/dev` does.

**Comment by yesmeck** [comment]
Oh, I think I know why it doesn't work now. `remix-routes` relies on `@remix-run/dev` to get route information. However, when you run `remix-routes`, `@remix-run/dev` doesn't recognize that you are using Vite.

**Comment by yesmeck** [comment]
I'm working on a Vite plugin to address this issue.

**Comment by yesmeck** [comment]
I just released `remix-routes@1.7.0` with a [Vite plugin](https://github.com/yesmeck/remix-routes?tab=readme-ov-file#with-vite). It should work better with Vite now.

**Comment by depsimon** [comment]
> I just released `remix-routes@1.7.0` with a [Vite plugin](https://github.com/yesmeck/remix-routes?tab=readme-ov-file#with-vite). It should work better with Vite now.

How do you recommend to use this in a CI environment?

Are we supposed to build/dev before running `tsc` to make sure the routes types are generated or should we commit the route definition?

**Comment by yesmeck** [comment]
> > I just released `remix-routes@1.7.0` with a [Vite plugin](https://github.com/yesmeck/remix-routes?tab=readme-ov-file#with-vite). It should work better with Vite now.
> 
> How do you recommend to use this in a CI environment?
> 
> Are we supposed to build/dev before running `tsc` to make sure the routes types are generated or should we commit the route definition?

I’m running a build in CI. If your app is large and the build is slow, you can emit the definition to somewhere other than node_modules with `outDir` option and commit it.
